"""Initial schema with segments

Revision ID: 0230a741c9b0
Revises: 
Create Date: 2026-01-19 18:50:18.356513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import backend.models


# revision identifiers, used by Alembic.
revision: str = '0230a741c9b0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('access_token', backend.models.EncryptedString(), nullable=False),
    sa.Column('refresh_token', backend.models.EncryptedString(), nullable=False),
    sa.Column('expires_at', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tokens_id'), 'tokens', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tokens_id'), table_name='tokens')
    op.drop_table('tokens')
    # ### end Alembic commands ###
